/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id?: string;
            email?: string;
        };
        AuthTokens: {
            access?: Record<string, never>;
            refresh?: Record<string, never>;
        };
        UserWithTokens: {
            user?: components["schemas"]["User"];
            tokens?: components["schemas"]["AuthTokens"];
        };
        Workspace: {
            _id?: string;
            name?: string;
            slug?: string;
            organizationType?: string;
            placeType?: string;
            settings?: Record<string, never>;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        IntegrationSettings: {
            _id?: string;
            workspaceId?: string;
            integrationId?: string;
            config?: Record<string, never>;
            isActive?: boolean;
            lastTestResult?: Record<string, never>;
            /** Format: date-time */
            lastTestAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        TestResult: {
            success?: boolean;
            message?: string;
            /** Format: date-time */
            timestamp?: string;
            details?: Record<string, never>;
        };
        IyzicoConfig: {
            enabled?: boolean;
            apiKey?: string;
            secretKey?: string;
            uri?: string;
        };
        MngConfig: {
            enabled?: boolean;
            apiKey?: string;
            apiSecret?: string;
        };
        TwilioConfig: {
            enabled?: boolean;
            accountSid?: string;
            authToken?: string;
            phoneNumber?: string;
        };
        SlackConfig: {
            enabled?: boolean;
            webhookUrl?: string;
            channel?: string;
            username?: string;
        };
        DiscordConfig: {
            enabled?: boolean;
            webhookUrl?: string;
            channel?: string;
            username?: string;
        };
        HubSpotConfig: {
            enabled?: boolean;
            apiKey?: string;
            portalId?: string;
        };
        SalesforceConfig: {
            enabled?: boolean;
            clientId?: string;
            clientSecret?: string;
            username?: string;
            password?: string;
            securityToken?: string;
        };
        SendGridConfig: {
            enabled?: boolean;
            apiKey?: string;
            fromEmail?: string;
            fromName?: string;
        };
        MailgunConfig: {
            enabled?: boolean;
            apiKey?: string;
            domain?: string;
            fromEmail?: string;
            fromName?: string;
        };
        ClickUpConfig: {
            enabled?: boolean;
            apiKey?: string;
            teamId?: string;
            spaceId?: string;
            folderId?: string;
            listId?: string;
        };
        EmailIntegrationSettings: {
            /** @enum {string} */
            provider?: "mailjet" | "gmail_smtp" | "custom_smtp" | "sendgrid" | "mailgun";
            enabled?: boolean;
            mailjet?: components["schemas"]["MailjetConfig"];
            sendgrid?: components["schemas"]["SendGridConfig"];
            mailgun?: components["schemas"]["MailgunConfig"];
            gmailSmtp?: components["schemas"]["GmailSmtpConfig"];
            customSmtp?: components["schemas"]["CustomSmtpConfig"];
        };
        MailjetConfig: {
            apiKey?: string;
            apiSecret?: string;
            fromEmail?: string;
            fromName?: string;
            templates?: Record<string, never>;
        };
        GmailSmtpConfig: {
            clientId?: string;
            clientSecret?: string;
            refreshToken?: string;
            fromEmail?: string;
            fromName?: string;
            templates?: Record<string, never>;
        };
        CustomSmtpConfig: {
            host?: string;
            port?: number;
            secure?: boolean;
            auth?: {
                user?: string;
                pass?: string;
            };
            fromEmail?: string;
            fromName?: string;
            templates?: Record<string, never>;
        };
        EmailTemplate: {
            /** @enum {string} */
            type?: "welcome" | "validation" | "password_reset" | "order_created" | "order_notification" | "event_registration" | "newsletter" | "contact_form";
            templateId?: string;
            subject?: string;
            content?: string;
            variables?: string[];
        };
        IntegrationInfo: {
            id?: string;
            name?: string;
            description?: string;
            category?: string;
            logo?: string;
            website?: string;
            documentation?: string;
            features?: string[];
        };
        Error: {
            status?: string;
            message?: string;
            error?: string;
        };
        SuccessResponse: {
            status?: string;
            data?: Record<string, never>;
            message?: string;
        };
        Menu: {
            _id?: string;
            /** @description Menü adı */
            name: string;
            /** @description Menü açıklaması */
            description?: string;
            /** @description Menü konumu (header, footer, sidebar vb.) */
            location: string;
            /** @description Menü öğeleri */
            items?: components["schemas"]["MenuItem"][];
            /** @description Menü aktif mi? */
            isActive?: boolean;
            metadata?: components["schemas"]["Metadata"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        MenuItem: {
            _id?: string;
            /** @description Menü öğesi başlığı */
            title: string;
            /** @description Menü öğesi URL'i */
            url: string;
            /** @description Menü öğesi ikonu */
            icon?: string;
            /** @description Menü öğesi sırası */
            order: number;
            /** @description Üst menü öğesi */
            parent?: components["schemas"]["MenuItem"];
            /** @description Alt menü öğeleri */
            children?: components["schemas"]["MenuItem"][];
            /** @description Menü öğesi aktif mi? */
            isActive?: boolean;
            /** @description Bu öğenin bulunduğu menüler */
            menus: components["schemas"]["Menu"][];
            /** @description Menü öğesi kategorisi */
            category?: components["schemas"]["MenuCategory"];
            metadata?: components["schemas"]["Metadata"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        MenuCategory: {
            _id?: string;
            /** @description Kategori başlığı */
            title: string;
            /** @description Kategori slug'ı */
            slug: string;
            /** @description Kategori açıklaması */
            description: string;
            /** @description Kategori öğeleri */
            items?: components["schemas"]["MenuItem"][];
            /** @description Üst kategori */
            parent?: components["schemas"]["MenuCategory"];
            /** @description Alt kategoriler */
            children?: components["schemas"]["MenuCategory"][];
            metadata?: components["schemas"]["Metadata"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Metadata: {
            published?: {
                /** Format: date-time */
                date?: string;
                by?: string;
            };
            edited?: {
                /** Format: date-time */
                date?: string;
                by?: string;
            }[];
            created?: {
                /** Format: date-time */
                date?: string;
                by?: string;
            };
        };
        CreateMenuDto: {
            /** @description Menü adı */
            name: string;
            /** @description Menü açıklaması */
            description?: string;
            /** @description Menü konumu */
            location: string;
            /** @description Menü aktif mi? */
            isActive?: boolean;
        };
        UpdateMenuDto: {
            /** @description Menü adı */
            name?: string;
            /** @description Menü açıklaması */
            description?: string;
            /** @description Menü konumu */
            location?: string;
            /** @description Menü aktif mi? */
            isActive?: boolean;
        };
        CreateMenuItemDto: {
            /** @description Menü öğesi başlığı */
            title: string;
            /** @description Menü öğesi URL'i */
            url: string;
            /** @description Menü öğesi ikonu */
            icon?: string;
            /** @description Menü öğesi sırası */
            order: number;
            /** @description Üst menü öğesi ID'si */
            parent?: string;
            /** @description Menü öğesi aktif mi? */
            isActive?: boolean;
            /** @description Bu öğenin bulunacağı menü ID'leri */
            menus: string[];
            /** @description Kategori ID'si */
            category?: string;
        };
        UpdateMenuItemDto: {
            /** @description Menü öğesi başlığı */
            title?: string;
            /** @description Menü öğesi URL'i */
            url?: string;
            /** @description Menü öğesi ikonu */
            icon?: string;
            /** @description Menü öğesi sırası */
            order?: number;
            /** @description Üst menü öğesi ID'si */
            parent?: string;
            /** @description Menü öğesi aktif mi? */
            isActive?: boolean;
            /** @description Bu öğenin bulunacağı menü ID'leri */
            menus?: string[];
            /** @description Kategori ID'si */
            category?: string;
        };
        CreateMenuCategoryDto: {
            /** @description Kategori başlığı */
            title: string;
            /** @description Kategori slug'ı */
            slug: string;
            /** @description Kategori açıklaması */
            description: string;
            /** @description Üst kategori ID'si */
            parent?: string;
        };
        UpdateMenuCategoryDto: {
            /** @description Kategori başlığı */
            title?: string;
            /** @description Kategori slug'ı */
            slug?: string;
            /** @description Kategori açıklaması */
            description?: string;
            /** @description Üst kategori ID'si */
            parent?: string;
        };
    };
    responses: {
        /** @description Email already taken */
        DuplicateEmail: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
