/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register as user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        /**
                         * Format: email
                         * @description must be unique
                         */
                        email: string;
                        /**
                         * Format: password
                         * @description At least one number and one letter
                         */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user?: components["schemas"]["User"];
                            tokens?: components["schemas"]["AuthTokens"];
                        };
                    };
                };
                400: components["responses"]["DuplicateEmail"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user?: components["schemas"]["User"];
                            tokens?: components["schemas"]["AuthTokens"];
                        };
                    };
                };
                /** @description Invalid email or password */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "code": 401,
                         *       "message": "Invalid email or password"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh auth tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserWithTokens"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/check-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check if email is registered
         * @description Check if an email address is registered in the current workspace
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Email check completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Whether the email is registered */
                            isValid?: boolean;
                            /** @description Status message */
                            message?: string;
                            /** @description Workspace information (only if email is valid) */
                            workspace?: {
                                /** @description Workspace ID */
                                id?: string;
                                /** @description User role in workspace */
                                role?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend OTP code
         * @description Request a new OTP code if the previous one expired or was not received
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        /**
                         * @description OTP delivery method (SMS currently deactive)
                         * @default email
                         * @enum {string}
                         */
                        method?: "sms" | "email";
                    };
                };
            };
            responses: {
                /** @description New OTP sent successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example New OTP code sent to email */
                            message?: string;
                            /** @example email */
                            method?: string;
                        };
                    };
                };
                /** @description Bad request (email not found) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "code": 400,
                         *       "message": "Email not found"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot password
         * @description An OTP code will be sent to email or SMS to reset password.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        /**
                         * @description OTP delivery method (SMS currently deactive)
                         * @default email
                         * @enum {string}
                         */
                        method?: "sms" | "email";
                    };
                };
            };
            responses: {
                /** @description OTP sent successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example OTP code sent to email */
                            message?: string;
                            /** @example email */
                            method?: string;
                        };
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password with OTP */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @description User's email address
                         */
                        email: string;
                        /** @description 6-digit OTP code received via email/SMS */
                        otp: string;
                        /**
                         * Format: password
                         * @description At least one number and one letter
                         */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Password reset successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Password reset successfully */
                            message?: string;
                        };
                    };
                };
                /** @description Invalid or expired OTP code */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "code": 400,
                         *       "message": "Invalid or expired OTP code"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Password reset failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "code": 401,
                         *       "message": "Password reset failed"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/send-verification-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send verification email
         * @description An email will be sent to verify email.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** verify email */
        post: {
            parameters: {
                query: {
                    /** @description The verify email token */
                    token: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description verify email failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "code": 401,
                         *       "message": "verify email failed"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify OTP code
         * @description Verify OTP code and get reset password token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        /** @description 6-digit OTP code */
                        otp: string;
                    };
                };
            };
            responses: {
                /** @description OTP verified successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example OTP verified successfully */
                            message?: string;
                            /** @description Token to use for reset password */
                            resetPasswordToken?: string;
                        };
                    };
                };
                /** @description Invalid or expired OTP */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "code": 400,
                         *       "message": "Invalid or expired OTP code"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Yeni workspace oluştur */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Workspace adı */
                        name: string;
                        /** @description Workspace slug */
                        slug: string;
                        /** @description Organizasyon tipi */
                        organizationType?: string;
                        /** @description Yer tipi */
                        placeType?: string;
                    };
                };
            };
            responses: {
                /** @description Workspace başarıyla oluşturuldu */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Geçersiz veri */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspace/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace listesini getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Workspace listesi başarıyla getirildi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            data?: components["schemas"]["Workspace"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspace/list/short": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kısa workspace listesini getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Kısa workspace listesi başarıyla getirildi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspace/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace takım üyelerini getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Takım üyeleri başarıyla getirildi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspace/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tüm settings'leri getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tüm settings başarıyla getirildi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example success */
                            status?: string;
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Workspace ID eksik */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Workspace bulunamadı */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspace/theme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace temasını getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Workspace teması başarıyla getirildi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Workspace temasını güncelle */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        theme?: Record<string, never>;
                    };
                };
            };
            responses: {
                /** @description Workspace teması başarıyla güncellendi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspace/management/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace detaylarını getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Workspace ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Workspace detayları başarıyla getirildi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Workspace"];
                    };
                };
            };
        };
        /** Workspace güncelle */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Workspace ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        slug?: string;
                        organizationType?: string;
                        placeType?: string;
                        settings?: Record<string, never>;
                    };
                };
            };
            responses: {
                /** @description Workspace başarıyla güncellendi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspace/settings/reset/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Settings'i sıfırla */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sıfırlanacak settings tipi */
                    type: "product" | "event" | "labelling" | "all";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Settings başarıyla sıfırlandı */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example success */
                            status?: string;
                            /** @example product settings reset successfully */
                            message?: string;
                        };
                    };
                };
                /** @description Geçersiz settings tipi */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Workspace bulunamadı */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menu/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tüm menü öğelerini listele (Yönetim) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Menü öğeleri başarıyla listelendi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            data?: components["schemas"]["MenuItem"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Yeni menü öğesi oluştur */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateMenuItemDto"];
                };
            };
            responses: {
                /** @description Menü öğesi başarıyla oluşturuldu */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            data?: components["schemas"]["MenuItem"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menu/items/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aktif menü öğelerini listele (Kullanıcı) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Aktif menü öğeleri başarıyla listelendi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            data?: components["schemas"]["MenuItem"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menu/items/{_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Menü öğesi detayını getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Menü öğesi ID */
                    _id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Menü öğesi detayı başarıyla getirildi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            data?: components["schemas"]["MenuItem"];
                        };
                    };
                };
            };
        };
        /** Menü öğesi güncelle */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Menü öğesi ID */
                    _id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateMenuItemDto"];
                };
            };
            responses: {
                /** @description Menü öğesi başarıyla güncellendi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            data?: components["schemas"]["MenuItem"];
                        };
                    };
                };
            };
        };
        post?: never;
        /** Menü öğesi sil */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Menü öğesi ID */
                    _id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Menü öğesi başarıyla silindi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            message?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Integration catalog'unu getir (filtreleme ile) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/catalog/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog'da arama yap */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/catalog/featured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Öne çıkan integration'ları getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/catalog/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Popüler integration'ları getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/catalog/category/:category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kategoriye göre integration'ları getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/catalog/plan/:plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan'a göre integration'ları getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/catalog/:type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Belirli bir integration'ın catalog item'ını getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/catalog/:type/guide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Integration guide'ını getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/catalog/:type/setup-steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Integration setup steps'lerini getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/:type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Integration config'ini getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        /** Integration'ı yapılandır */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        post?: never;
        /** Integration'ı sil */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/:type/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Integration'ı aktif et */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/:type/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Integration'ı pasif et */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/:type/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Integration'ı test et */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tüm integration status'lerini getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/status/:type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Belirli bir integration status'ünü getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Integration kategorilerini getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all outgoing webhooks for the workspace */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        /** Create a new outgoing webhook */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update an existing outgoing webhook */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        post?: never;
        /** Delete an outgoing webhook */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id?: string;
            email?: string;
        };
        AuthTokens: {
            access?: Record<string, never>;
            refresh?: Record<string, never>;
        };
        UserWithTokens: {
            user?: components["schemas"]["User"];
            tokens?: components["schemas"]["AuthTokens"];
        };
        Workspace: {
            _id?: string;
            name?: string;
            slug?: string;
            organizationType?: string;
            placeType?: string;
            settings?: Record<string, never>;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        IntegrationSettings: {
            _id?: string;
            workspaceId?: string;
            integrationId?: string;
            config?: Record<string, never>;
            isActive?: boolean;
            lastTestResult?: Record<string, never>;
            /** Format: date-time */
            lastTestAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        TestResult: {
            success?: boolean;
            message?: string;
            /** Format: date-time */
            timestamp?: string;
            details?: Record<string, never>;
        };
        IyzicoConfig: {
            enabled?: boolean;
            apiKey?: string;
            secretKey?: string;
            uri?: string;
        };
        MngConfig: {
            enabled?: boolean;
            apiKey?: string;
            apiSecret?: string;
        };
        TwilioConfig: {
            enabled?: boolean;
            accountSid?: string;
            authToken?: string;
            phoneNumber?: string;
        };
        SlackConfig: {
            enabled?: boolean;
            webhookUrl?: string;
            channel?: string;
            username?: string;
        };
        DiscordConfig: {
            enabled?: boolean;
            webhookUrl?: string;
            channel?: string;
            username?: string;
        };
        HubSpotConfig: {
            enabled?: boolean;
            apiKey?: string;
            portalId?: string;
        };
        SalesforceConfig: {
            enabled?: boolean;
            clientId?: string;
            clientSecret?: string;
            username?: string;
            password?: string;
            securityToken?: string;
        };
        SendGridConfig: {
            enabled?: boolean;
            apiKey?: string;
            fromEmail?: string;
            fromName?: string;
        };
        MailgunConfig: {
            enabled?: boolean;
            apiKey?: string;
            domain?: string;
            fromEmail?: string;
            fromName?: string;
        };
        ClickUpConfig: {
            enabled?: boolean;
            apiKey?: string;
            teamId?: string;
            spaceId?: string;
            folderId?: string;
            listId?: string;
        };
        EmailIntegrationSettings: {
            /** @enum {string} */
            provider?: "mailjet" | "gmail_smtp" | "custom_smtp" | "sendgrid" | "mailgun";
            enabled?: boolean;
            mailjet?: components["schemas"]["MailjetConfig"];
            sendgrid?: components["schemas"]["SendGridConfig"];
            mailgun?: components["schemas"]["MailgunConfig"];
            gmailSmtp?: components["schemas"]["GmailSmtpConfig"];
            customSmtp?: components["schemas"]["CustomSmtpConfig"];
        };
        MailjetConfig: {
            apiKey?: string;
            apiSecret?: string;
            fromEmail?: string;
            fromName?: string;
            templates?: Record<string, never>;
        };
        GmailSmtpConfig: {
            clientId?: string;
            clientSecret?: string;
            refreshToken?: string;
            fromEmail?: string;
            fromName?: string;
            templates?: Record<string, never>;
        };
        CustomSmtpConfig: {
            host?: string;
            port?: number;
            secure?: boolean;
            auth?: {
                user?: string;
                pass?: string;
            };
            fromEmail?: string;
            fromName?: string;
            templates?: Record<string, never>;
        };
        EmailTemplate: {
            /** @enum {string} */
            type?: "welcome" | "validation" | "password_reset" | "order_created" | "order_notification" | "event_registration" | "newsletter" | "contact_form";
            templateId?: string;
            subject?: string;
            content?: string;
            variables?: string[];
        };
        IntegrationInfo: {
            id?: string;
            name?: string;
            description?: string;
            category?: string;
            logo?: string;
            website?: string;
            documentation?: string;
            features?: string[];
        };
        Error: {
            status?: string;
            message?: string;
            error?: string;
        };
        SuccessResponse: {
            status?: string;
            data?: Record<string, never>;
            message?: string;
        };
        Menu: {
            _id?: string;
            /** @description Menü adı */
            name: string;
            /** @description Menü açıklaması */
            description?: string;
            /** @description Menü konumu (header, footer, sidebar vb.) */
            location: string;
            /** @description Menü öğeleri */
            items?: components["schemas"]["MenuItem"][];
            /** @description Menü aktif mi? */
            isActive?: boolean;
            metadata?: components["schemas"]["Metadata"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        MenuItem: {
            _id?: string;
            /** @description Menü öğesi başlığı */
            title: string;
            /** @description Menü öğesi URL'i */
            url: string;
            /** @description Menü öğesi ikonu */
            icon?: string;
            /** @description Menü öğesi sırası */
            order: number;
            /** @description Üst menü öğesi */
            parent?: components["schemas"]["MenuItem"];
            /** @description Alt menü öğeleri */
            children?: components["schemas"]["MenuItem"][];
            /** @description Menü öğesi aktif mi? */
            isActive?: boolean;
            /** @description Bu öğenin bulunduğu menüler */
            menus: components["schemas"]["Menu"][];
            /** @description Menü öğesi kategorisi */
            category?: components["schemas"]["MenuCategory"];
            metadata?: components["schemas"]["Metadata"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        MenuCategory: {
            _id?: string;
            /** @description Kategori başlığı */
            title: string;
            /** @description Kategori slug'ı */
            slug: string;
            /** @description Kategori açıklaması */
            description: string;
            /** @description Kategori öğeleri */
            items?: components["schemas"]["MenuItem"][];
            /** @description Üst kategori */
            parent?: components["schemas"]["MenuCategory"];
            /** @description Alt kategoriler */
            children?: components["schemas"]["MenuCategory"][];
            metadata?: components["schemas"]["Metadata"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Metadata: {
            published?: {
                /** Format: date-time */
                date?: string;
                by?: string;
            };
            edited?: {
                /** Format: date-time */
                date?: string;
                by?: string;
            }[];
            created?: {
                /** Format: date-time */
                date?: string;
                by?: string;
            };
        };
        CreateMenuDto: {
            /** @description Menü adı */
            name: string;
            /** @description Menü açıklaması */
            description?: string;
            /** @description Menü konumu */
            location: string;
            /** @description Menü aktif mi? */
            isActive?: boolean;
        };
        UpdateMenuDto: {
            /** @description Menü adı */
            name?: string;
            /** @description Menü açıklaması */
            description?: string;
            /** @description Menü konumu */
            location?: string;
            /** @description Menü aktif mi? */
            isActive?: boolean;
        };
        CreateMenuItemDto: {
            /** @description Menü öğesi başlığı */
            title: string;
            /** @description Menü öğesi URL'i */
            url: string;
            /** @description Menü öğesi ikonu */
            icon?: string;
            /** @description Menü öğesi sırası */
            order: number;
            /** @description Üst menü öğesi ID'si */
            parent?: string;
            /** @description Menü öğesi aktif mi? */
            isActive?: boolean;
            /** @description Bu öğenin bulunacağı menü ID'leri */
            menus: string[];
            /** @description Kategori ID'si */
            category?: string;
        };
        UpdateMenuItemDto: {
            /** @description Menü öğesi başlığı */
            title?: string;
            /** @description Menü öğesi URL'i */
            url?: string;
            /** @description Menü öğesi ikonu */
            icon?: string;
            /** @description Menü öğesi sırası */
            order?: number;
            /** @description Üst menü öğesi ID'si */
            parent?: string;
            /** @description Menü öğesi aktif mi? */
            isActive?: boolean;
            /** @description Bu öğenin bulunacağı menü ID'leri */
            menus?: string[];
            /** @description Kategori ID'si */
            category?: string;
        };
        CreateMenuCategoryDto: {
            /** @description Kategori başlığı */
            title: string;
            /** @description Kategori slug'ı */
            slug: string;
            /** @description Kategori açıklaması */
            description: string;
            /** @description Üst kategori ID'si */
            parent?: string;
        };
        UpdateMenuCategoryDto: {
            /** @description Kategori başlığı */
            title?: string;
            /** @description Kategori slug'ı */
            slug?: string;
            /** @description Kategori açıklaması */
            description?: string;
            /** @description Üst kategori ID'si */
            parent?: string;
        };
    };
    responses: {
        /** @description Email already taken */
        DuplicateEmail: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
